// ------------------------------------
// Constants
// ------------------------------------
export const CUSTOMERS_REQUEST = 'CUSTOMERS_REQUEST';
export const CUSTOMERS_SUCCESS = 'CUSTOMERS_SUCCESS';
export const CUSTOMERS_FAIL = 'CUSTOMERS_FAIL';

export const BLOCK_CUSTOMER_REQUEST = 'BLOCK_CUSTOMER_REQUEST';
export const BLOCK_CUSTOMER_SUCCESS = 'BLOCK_CUSTOMER_SUCCESS';
export const BLOCK_CUSTOMER_FAIL = 'BLOCK_CUSTOMER_FAIL';

export const REINVITE_CUSTOMER_REQUEST = 'REINVITE_CUSTOMER_REQUEST';
export const REINVITE_CUSTOMER_SUCCESS = 'REINVITE_CUSTOMER_SUCCESS';
export const REINVITE_CUSTOMER_FAIL = 'REINVITE_CUSTOMER_FAIL';

export const CREATE_CUSTOMER_REQUEST = 'CREATE_CUSTOMER_REQUEST';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_FAIL = 'CREATE_CUSTOMER_FAIL';

export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_FAIL = 'UPDATE_CUSTOMER_FAIL';